sudo: false
language: java
jdk:
  - openjdk11

install: true

script:
  - sh -n *.sh          # check syntax of scripts
  - sh -n src/*.sh      # check syntax of scripts
  - src/mvn-run.sh  -v  # execute always
  - src/mvn-push.sh -v  # execute on push
  - src/mvn-pr.sh   -v  # execute on PR
  - src/mvn-tag.sh   -v # execute on git tag
