sudo: false
language: java
jdk:
  - oraclejdk8

install: true

script:
  - sh -n src/*.sh      # check syntax of scripts
  - src/mvn-push.sh -v  # execute on push
  - src/mvn-pr.sh   -v  # execute on PR
