# standard jobs

branches:
  only:
    - master
    - /^v\d+(\.\d+)*$/

# turn shallow clone off for sonar
git:
  depth: false

jobs:
  include:

    - name: "jdk11"
      jdk: openjdk11
      script: >-
        ../utils/mvn-push.sh    clean deploy  &&
        ../utils/mvn-pr.sh      clean verify  &&
        ../utils/mvn-tag.sh     clean site    &&
        ../utils/mvn-sonar.sh   sonar:sonar
      if: repo = env(MY_REPO)

    - name: "jdk11 - forks"
      jdk: openjdk11
      script:
        - ../utils/mvn-run.sh     clean verify
      if: repo != env(MY_REPO)
