# standard jobs

# turn shallow clone off for sonar
git:
  depth: false

addons:
  sonarcloud:
    organization: $SONAR_ORG

jobs:
  include:

    - name: "jdk8"
      jdk: openjdk8
      script: >-
        ../utils/mvn-push.sh    clean deploy  &&
        ../utils/mvn-pr.sh      clean verify  &&
        ../utils/mvn-tag.sh     clean site    &&
        ../utils/mvn-sonar.sh   sonar:sonar
      if: repo = env(MY_REPO)

    - name: "jdk8 - forks"
      jdk: openjdk8
      script:
        - ../utils/mvn-run.sh     clean verify
      if: repo != env(MY_REPO)

    - name: "jdk11"
      jdk: openjdk11
      script:
        - ../utils/mvn-run.sh     clean verify
