#!/bin/sh

echo "+++ PRINT-ENV +++"

echo "TRAVIS_SECURE_ENV_VARS     = $TRAVIS_SECURE_ENV_VARS"
echo "TRAVIS_EVENT_TYPE          = $TRAVIS_EVENT_TYPE"

echo "TRAVIS_COMMIT              = $TRAVIS_COMMIT"
echo "TRAVIS_COMMIT_MESSAGE      = $TRAVIS_COMMIT_MESSAGE"
echo "TRAVIS_TAG                 = $TRAVIS_TAG"
echo "TRAVIS_REPO_SLUG           = $TRAVIS_REPO_SLUG"
echo "TRAVIS_BRANCH              = $TRAVIS_BRANCH"

echo "TRAVIS_PULL_REQUEST        = $TRAVIS_PULL_REQUEST"
echo "TRAVIS_PULL_REQUEST_SLUG   = $TRAVIS_PULL_REQUEST_SLUG"
echo "TRAVIS_PULL_REQUEST_BRANCH = $TRAVIS_PULL_REQUEST_BRANCH"

echo "JAVA_HOME                  = $JAVA_HOME"

echo "+++ PRINT-ENV +++"
